export const config = {
    defoldAnnotationsFolder: '.defold/api',
    defoldTealTypesFolder: 'types',
    defoldTealTypesFile: 'defold.d.tl', // should match the file generated by https://github.com/robknopf/defold-lsp-annotations/releases
    assetsAnnotationsFolder: '.defold/assets',
    lastMigration: 2,
    outputChannelName: 'Defold Buddy',
};
